---
http_interactions:
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/api/urls
    body:
      encoding: UTF-8
      string: '{"url":"http://bsd.de"}'
    headers:
      Accept:
      - "*/*"
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '23'
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://127.0.0.1:8080/hawkular/inventory/deprecated/test/resources/536cc3ede5769b60a49774425aedba24
      Date:
      - Thu, 14 Jul 2016 16:23:37 GMT
      Connection:
      - keep-alive
      Content-Length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 14 Jul 2016 16:23:37 GMT
recorded_with: VCR 3.0.1
