sudo: required

language: ruby
rvm:
  - 2.2
  - 2.3.0
env:
  global:
    - ADMIN_TOKEN=4f4a1434-8cb3-11e6-ae22-56b6b6499611
    # GH_TOKEN=...  used by hawkular-website-bot to publish the documentation
    - secure: "g74r/WaW7+aZdRCY5aO8BM6xH2fKDasmTo4hMgDEdnG97MxNoZxcPZL6cUtUt4eYK/3mSRtm0fToc9fl6cf+cTAL280CeOVznJnMWaItYcCYiq4Q/SbhzLE4AVanSO75rV6FwAmz0M962wykLboo81KfbJ/IRsDVDcyyfcjrAq2p5Jla0Cv0fMw1Mvt/ededkDxVv56EyEtrF8uCPPLhoi9l47Xz6I7nHl1aXgy5hoT0gghKlKuSeZWVC+D7p1YQioMdTLaTSKjxcx9gX+ikMryju7hpvlQ4CwVp396QTu+olFKDochxI6usbrL2dE7z459zePAMU47uiQhVwOqwaddqSzXgqcE/k12Q7VMpBvyXMN9Y7ySTLAf7E7HJIFeLgv679wWeBiZ9+zWTIIBfKdXHf47SlMpAAujjuQk+mwA6LpIamZd7UZVXw/ryOKqj/+8oE/uSGq+9Y8AA1bjKBBe0meuN6zJ3fRPoDzHyYJJe8zDwGox0dSKQXtExSnl6KJjDunlJmkca7aJwSf9Nr8/lIxsD8/bgUlKHY72f87Xs9lRlHw7rmblEw5Biqk/qLmcvtEIY8Vi6CsXjWnVNipq9rmc12HDSj5Mzj5vtehjIzpoHC8/QSqNlVFMPcTmweTeSGMjwn/KrR02GG/mwNbphHiu2vvP6G2LUr1yIj2o="
  matrix:
    - RUN_ON_LIVE_SERVER=1 \
      VCR_UPDATE=1 \
      SKIP_SSL_WITHOUT_CERTIFICATE_TEST=1 \
      SKIP_SECURE_CONTEXT=1 \
      SKIP_V8_METRICS=1 \
    - RUN_ON_LIVE_SERVER=0
services:
  - docker
before_install:
  - (test $RUN_ON_LIVE_SERVER = 1 && ./.travis/start_hawkular_services.sh -d && ./.travis/wait_for_services.rb) || echo "Skipping live server"
after_success:
  - ./.travis.docs.rb
