sudo: required

language: ruby
rvm:
  - 2.2
  - 2.3.0
env:
  global:
    - ADMIN_TOKEN=4f4a1434-8cb3-11e6-ae22-56b6b6499611
    # GH_TOKEN=...  used by hawkular-website-bot to publish the documentation
    - secure: "SJykGUwG52ay+6mgIgo/hjOO9CpLFCiccE+ua2JXlwOMjkE49+9WmxL0osiZFpr76wsxTK6OvQweX8NiCm9ABYXanWY6929vBJuwmpqeZRcPU2JgBwZohYc8SMU4pk240A15Pq97WPs2MUTPPEylceDv+ZFv8JRbPqDn73wEqDkOU9PwOendOLjT0pyRlBADxLAP3rm4uaE5D4bxj5lG/9EaVUA5gvnTz2PdfFlgy5QumJK+d8GhQhaqTwtJ/P3TxfNDVz539MBdHRlw6JJil0lWHYe9xAfwb9pnSs0JMT987RkzbG7w6gRaRUo9+ZC4q/6jc9sIcqHOGoc4f/aNu9MDEVsj7kD9s1UZmZwOB3jVmIllAsZwOefntZ+oQJJCjbQ2V5kJ+V2d9ATj2i8WaoeBTAUC2t6V8IGOWKZya7LmNp6Mud5zJmrBSEM4OjbPxICCEYLHL7tX9U4ipKxlqf0pChoO0jh9Ea0v3lzxdOeErtDXlnBkikxbNL160uCXbZDxydHCP2GS76UnjxY33QnXUCj2wYmJjZJ/Tq6s2sEVvPftxmq5bT0v2KMq0+hb4ySyUgR2Via7t5jxkSM86Hw1nxKf88RxXoEGXxF75tpgi5vtOZRPIBbiUo33XroWk/kU/KElg7vhTlt+4G6G7nVYiANhSLcpIzKW3BqwQD4="
  matrix:
    - RUN_ON_LIVE_SERVER=1 \
      VCR_UPDATE=1 \
      SKIP_SSL_WITHOUT_CERTIFICATE_TEST=1 \
      SKIP_SECURE_CONTEXT=1 \
      SKIP_V8_METRICS=1 \
    - RUN_ON_LIVE_SERVER=0
services:
  - docker
before_install:
  - (test $RUN_ON_LIVE_SERVER = 1 && ./.travis/start_hawkular_services.sh -d && ./.travis/wait_for_services.rb) || echo "Skipping live server"
after_success:
  - ./.travis.docs.rb
