---
http_interactions:
- request:
    method: post
    uri: https://jdoe:password@127.0.0.1:8443/hawkular/metrics/availability/<%= id %>/raw
    body:
      encoding: UTF-8
      string: '[{"timestamp":<%= minus50 %>,"value":"up"},{"timestamp":<%= minus40 %>,"value":"up"},{"timestamp":<%= minus30 %>,"value":"down"},{"timestamp":<%= minus20 %>,"value":"down"},{"timestamp":<%= minus10 %>,"value":"down"},{"timestamp":<%= now %>,"value":"up"}]'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - <%= vcr_test_tenant %>
      Content-Type:
      - application/json
      Content-Length:
      - '253'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Connection:
      - keep-alive
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Content-Length:
      - '0'
      Date:
      - Mon, 15 Aug 2016 15:20:42 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Mon, 15 Aug 2016 15:20:42 GMT
- request:
    method: get
    uri: https://jdoe:password@127.0.0.1:8443/hawkular/metrics/availability/<%= id %>/raw/?distinct=true&order=ASC
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - <%= vcr_test_tenant %>
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 15 Aug 2016 15:20:42 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '126'
    body:
      encoding: UTF-8
      string: '[{"timestamp":<%= minus50 %>,"value":"up"},{"timestamp":<%= minus30 %>,"value":"down"},{"timestamp":<%= now %>,"value":"up"}]'
    http_version: 
  recorded_at: Mon, 15 Aug 2016 15:20:42 GMT
recorded_with: VCR 3.0.3
