---
http_interactions:
- request:
    method: post
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/entity/feed
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_may_exist","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '79'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - https://127.0.0.1:8443/hawkular/inventory/entity/f;feed_may_exist
      Date:
      - Wed, 10 Aug 2016 22:35:50 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '135'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;feed_may_exist",
          "identityHash" : "18a4f8a18a8012f826e2dbe4cb768d14c391a59b",
          "id" : "feed_may_exist"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:50 GMT
- request:
    method: post
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/entity/f;feed_may_exist/resourceType
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"rt-123","name":"ResourceType","outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '81'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - https://127.0.0.1:8443/hawkular/inventory/entity/f;feed_may_exist/rt;rt-123
      Date:
      - Wed, 10 Aug 2016 22:35:50 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '162'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;feed_may_exist/rt;rt-123",
          "name" : "ResourceType",
          "identityHash" : "30a52c53a93cb102e499367ecc55ed8a03b0b1",
          "id" : "rt-123"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:50 GMT
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/entity/f;feed_may_exist/rt;rt-123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:50 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '162'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;feed_may_exist/rt;rt-123",
          "name" : "ResourceType",
          "identityHash" : "30a52c53a93cb102e499367ecc55ed8a03b0b1",
          "id" : "rt-123"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:50 GMT
recorded_with: VCR 3.0.3
