---
http_interactions:
- request:
    method: post
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/entity/feed
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_1123sdn","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '77'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - https://127.0.0.1:8443/hawkular/inventory/entity/f;feed_1123sdn
      Date:
      - Wed, 10 Aug 2016 22:35:50 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '131'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;feed_1123sdn",
          "identityHash" : "e153d6e14c5bd12f51dcdc16a0493afbd0298dcb",
          "id" : "feed_1123sdn"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:50 GMT
- request:
    method: delete
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/entity/f;feed_1123sdn
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 204
      message: No Content
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:50 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:50 GMT
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/traversal/type=f
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:50 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '540'
      Link:
      - <https://127.0.0.1:8443/hawkular/inventory/traversal/type=f>; rel="current"
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/f;<%= feed_uuid %>",
          "properties" : {
            "__identityHash" : "6f7052f82072f942f3e402fe127d6133ea5e963"
          },
          "identityHash" : "6f7052f82072f942f3e402fe127d6133ea5e963",
          "id" : "<%= feed_uuid %>"
        }, {
          "path" : "/t;hawkular/f;feed_1123sdncisud6237ui23hjbdscuzsad",
          "properties" : {
            "__identityHash" : "c5ef96a36ea11f6a72066f685b5d1d8b9d1daaf"
          },
          "identityHash" : "c5ef96a36ea11f6a72066f685b5d1d8b9d1daaf",
          "id" : "feed_1123sdncisud6237ui23hjbdscuzsad"
        } ]
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:50 GMT
recorded_with: VCR 3.0.3
