---
http_interactions:
- request:
    method: post
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/entity/feed
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_1123sdncisud6237ui2378789vvgX","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '99'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - https://127.0.0.1:8443/hawkular/inventory/entity/f;feed_1123sdncisud6237ui2378789vvgX
      Date:
      - Wed, 10 Aug 2016 22:35:50 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '173'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;feed_1123sdncisud6237ui2378789vvgX",
          "identityHash" : "55d3efb84276a901e3b5418316643249b078ab",
          "id" : "feed_1123sdncisud6237ui2378789vvgX"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:50 GMT
- request:
    method: post
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/entity/feed
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_1123sdncisud6237ui2378789vvgX","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '99'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:50 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '763'
    body:
      encoding: UTF-8
      string: |-
        {
          "errorMsg" : "Feed with id 'Feed[path='/t;hawkular/f;feed_1123sdncisud6237ui2378789vvgX']' has been already registered. Entity with id 'feed_1123sdncisud6237ui2378789vvgX' already exists at some of the positions: [[Types[Tenant], Ids[hawkular], Related[, rel='contains', role=SOURCE], Types[Feed], Ids[feed_1123sdncisud6237ui2378789vvgX]]]",
          "details" : {
            "entityId" : "feed_1123sdncisud6237ui2378789vvgX",
            "paths" : [ [ {
              "types" : [ "org.hawkular.inventory.api.model.Tenant" ]
            }, {
              "ids" : [ "hawkular" ]
            }, {
              "relationshipName" : "contains",
              "entityRole" : "SOURCE"
            }, {
              "types" : [ "org.hawkular.inventory.api.model.Feed" ]
            }, {
              "ids" : [ "feed_1123sdncisud6237ui2378789vvgX" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:50 GMT
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/entity/f;feed_1123sdncisud6237ui2378789vvgX
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:50 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '261'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;feed_1123sdncisud6237ui2378789vvgX",
          "properties" : {
            "__identityHash" : "55d3efb84276a901e3b5418316643249b078ab"
          },
          "identityHash" : "55d3efb84276a901e3b5418316643249b078ab",
          "id" : "feed_1123sdncisud6237ui2378789vvgX"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:50 GMT
recorded_with: VCR 3.0.3
