---
http_interactions:
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/traversal/f;<%= feed_uuid %>/rt;WildFly%20Server/rl;defines/type=r
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:49 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '519'
      Link:
      - <https://127.0.0.1:8443/hawkular/inventory/traversal/f;<%= feed_uuid %>/rt;WildFly%20Server/rl;defines/type=r>;
        rel="current"
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;Local~~",
          "properties" : {
            "__identityHash" : "a12d8e9f318357f8aeccd9d955146476325d8b8f"
          },
          "name" : "WildFly Server [Local]",
          "identityHash" : "a12d8e9f318357f8aeccd9d955146476325d8b8f",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/rt;WildFly%20Server",
            "name" : "WildFly Server",
            "identityHash" : "385d354c833f19e97d427c7bfc7c6441b73ef1c",
            "id" : "WildFly Server"
          },
          "id" : "Local~~"
        } ]
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:49 GMT
recorded_with: VCR 3.0.3
