---
http_interactions:
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/traversal/rt;URL/rl;defines/type=r
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 30 Aug 2016 16:03:30 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '1299'
      Link:
      - <https://127.0.0.1:8443/hawkular/inventory/traversal/rt;URL/rl;defines/type=r>;
        rel="current"
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/e;test/r;536cc3ede5769b60a49774425aedba24",
          "properties" : {
            "hwk-gui-domainSort" : "http://bsd.de",
            "url" : "http://bsd.de"
          },
          "identityHash" : "fdb7ef259d64dbec43139ca792be98c38156dfc",
          "contentHash" : "f2ebcfe621cea669aa1ca67421bfbb1bb5a38bd",
          "syncHash" : "f86374f837a67d517e2f07e1c6442adcbb8b",
          "type" : {
            "path" : "/t;hawkular/rt;URL",
            "identityHash" : "726212916beec584f8dcdcaf8beeb929620393c",
            "contentHash" : "da39a3ee5e6b4bd3255bfef95601890afd879",
            "syncHash" : "7c297bcbd591993d955298fac1cc93684f314021",
            "id" : "URL"
          },
          "id" : "536cc3ede5769b60a49774425aedba24"
        }, {
          "path" : "/t;hawkular/e;test/r;500f8d0217bb2fd4f674432ba9a9d827",
          "properties" : {
            "hwk-gui-domainSort" : "http://bsd.es",
            "url" : "http://bsd.es"
          },
          "identityHash" : "d1d693bbb5ea2c942d8d15515a22fe8dc64f399",
          "contentHash" : "d93a266ef420667f4b72e92744bf7d206454ae49",
          "syncHash" : "e45cf568afc9aa41fa3a66e15a0d6acd1632c0",
          "type" : {
            "path" : "/t;hawkular/rt;URL",
            "identityHash" : "726212916beec584f8dcdcaf8beeb929620393c",
            "contentHash" : "da39a3ee5e6b4bd3255bfef95601890afd879",
            "syncHash" : "7c297bcbd591993d955298fac1cc93684f314021",
            "id" : "URL"
          },
          "id" : "500f8d0217bb2fd4f674432ba9a9d827"
        } ]
    http_version: 
  recorded_at: Tue, 30 Aug 2016 16:03:30 GMT
recorded_with: VCR 3.0.3
