---
http_interactions:
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/raw/query
    body:
      encoding: UTF-8
      string: '{"fromEarliest":true,"order":"DESC","tags":"module:inventory,feed:bdc3ba51\\-e367\\-4696\\-b015\\-3ba83fd359fc,type:r,restypes:.*\\|URL\\|.*"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '142'
      Host:
      - localhost:8080
  response:
    status:
      code: 204
      message: No Content
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 29 Mar 2017 12:56:04 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 29 Mar 2017 12:56:04 GMT
recorded_with: VCR 3.0.3
