---
http_interactions:
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/entity/feed
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"<%= uuid_prefix %>-feed","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '106'
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed
      Date:
      - Thu, 14 Jul 2016 16:23:47 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '187'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed",
          "identityHash" : "23c0965c645ea9a9ff8a68c9332d3b64058a52",
          "id" : "<%= uuid_prefix %>-feed"
        }
    http_version: 
  recorded_at: Thu, 14 Jul 2016 16:23:47 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/resourceType
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"<%= uuid_prefix %>-rt-123","name":"ResourceType","outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '118'
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123
      Date:
      - Thu, 14 Jul 2016 16:23:47 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '262'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
          "name" : "ResourceType",
          "identityHash" : "e9c230bbc9d7c8403fe2cac5da66a8ff5b829",
          "id" : "<%= uuid_prefix %>-rt-123"
        }
    http_version: 
  recorded_at: Thu, 14 Jul 2016 16:23:47 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 14 Jul 2016 16:23:47 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '262'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
          "name" : "ResourceType",
          "identityHash" : "e9c230bbc9d7c8403fe2cac5da66a8ff5b829",
          "id" : "<%= uuid_prefix %>-rt-123"
        }
    http_version: 
  recorded_at: Thu, 14 Jul 2016 16:23:47 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/resource
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.0},"id":"<%= uuid_prefix %>-r126","name":"My
        Resource 1","outgoing":{},"incoming":{},"resourceTypePath":"/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '254'
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r126
      Date:
      - Thu, 14 Jul 2016 16:23:47 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '586'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r126",
          "properties" : {
            "version" : 1.0
          },
          "name" : "My Resource 1",
          "identityHash" : "97b5e40adef778ab8346c6f94fe54fa76033",
          "type" : {
            "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "identityHash" : "e9c230bbc9d7c8403fe2cac5da66a8ff5b829",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "id" : "<%= uuid_prefix %>-r126"
        }
    http_version: 
  recorded_at: Thu, 14 Jul 2016 16:23:47 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/resource
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.1},"id":"<%= uuid_prefix %>-r127","name":"My
        Resource 2","outgoing":{},"incoming":{},"resourceTypePath":"/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '254'
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r127
      Date:
      - Thu, 14 Jul 2016 16:23:47 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '587'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r127",
          "properties" : {
            "version" : 1.1
          },
          "name" : "My Resource 2",
          "identityHash" : "ea33ef47915a14e7d645d639d6f8bc38c7172",
          "type" : {
            "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "identityHash" : "e9c230bbc9d7c8403fe2cac5da66a8ff5b829",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "id" : "<%= uuid_prefix %>-r127"
        }
    http_version: 
  recorded_at: Thu, 14 Jul 2016 16:23:47 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/resource
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.2},"id":"<%= uuid_prefix %>-r128","name":"My
        Resource 3","outgoing":{},"incoming":{},"resourceTypePath":"/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '254'
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r128
      Date:
      - Thu, 14 Jul 2016 16:23:48 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '589'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r128",
          "properties" : {
            "version" : 1.2
          },
          "name" : "My Resource 3",
          "identityHash" : "e72792a8b2f0199c941ed3d0b54b66c4979ce22",
          "type" : {
            "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "identityHash" : "e9c230bbc9d7c8403fe2cac5da66a8ff5b829",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "id" : "<%= uuid_prefix %>-r128"
        }
    http_version: 
  recorded_at: Thu, 14 Jul 2016 16:23:48 GMT
- request:
    method: delete
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
  response:
    status:
      code: 204
      message: No Content
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 14 Jul 2016 16:23:48 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 14 Jul 2016 16:23:48 GMT
recorded_with: VCR 3.0.1
