---
http_interactions:
- request:
    method: post
    uri: https://<%= username %>:<%= password %>@127.0.0.1:8443/hawkular/inventory/entity/feed
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"<%= uuid_prefix %>-feed","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '106'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - https://127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed
      Date:
      - Wed, 10 Aug 2016 22:35:54 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '188'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed",
          "identityHash" : "29d98d196dab981166ca9268315fa0db2bd5a71",
          "id" : "<%= uuid_prefix %>-feed"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:54 GMT
- request:
    method: post
    uri: https://<%= username %>:<%= password %>@127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/resourceType
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"<%= uuid_prefix %>-rt-123","name":"ResourceType","outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '118'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - https://127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123
      Date:
      - Wed, 10 Aug 2016 22:35:54 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '264'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
          "name" : "ResourceType",
          "identityHash" : "5316c720e3ab6f14a74c20611d15bf71ecf2bad",
          "id" : "<%= uuid_prefix %>-rt-123"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:54 GMT
- request:
    method: get
    uri: https://<%= username %>:<%= password %>@127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:54 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '264'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
          "name" : "ResourceType",
          "identityHash" : "5316c720e3ab6f14a74c20611d15bf71ecf2bad",
          "id" : "<%= uuid_prefix %>-rt-123"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:54 GMT
- request:
    method: post
    uri: https://<%= username %>:<%= password %>@127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/resource
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.0},"id":"<%= uuid_prefix %>-r126","name":"My
        Resource 1","outgoing":{},"incoming":{},"resourceTypePath":"/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '254'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - https://127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r126
      Date:
      - Wed, 10 Aug 2016 22:35:54 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '591'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r126",
          "properties" : {
            "version" : 1.0
          },
          "name" : "My Resource 1",
          "identityHash" : "3ae2eca73915c0f178f9cd5ff9f910453ae2d7a",
          "type" : {
            "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "identityHash" : "5316c720e3ab6f14a74c20611d15bf71ecf2bad",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "id" : "<%= uuid_prefix %>-r126"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:54 GMT
- request:
    method: post
    uri: https://<%= username %>:<%= password %>@127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/resource
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.1},"id":"<%= uuid_prefix %>-r127","name":"My
        Resource 2","outgoing":{},"incoming":{},"resourceTypePath":"/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '254'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - https://127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r127
      Date:
      - Wed, 10 Aug 2016 22:35:54 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '591'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r127",
          "properties" : {
            "version" : 1.1
          },
          "name" : "My Resource 2",
          "identityHash" : "a927a976342b2638a1d2971953990cc3490c31d",
          "type" : {
            "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "identityHash" : "5316c720e3ab6f14a74c20611d15bf71ecf2bad",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "id" : "<%= uuid_prefix %>-r127"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:54 GMT
- request:
    method: post
    uri: https://<%= username %>:<%= password %>@127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/resource
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.2},"id":"<%= uuid_prefix %>-r128","name":"My
        Resource 3","outgoing":{},"incoming":{},"resourceTypePath":"/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '254'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - https://127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r128
      Date:
      - Wed, 10 Aug 2016 22:35:54 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '591'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r128",
          "properties" : {
            "version" : 1.2
          },
          "name" : "My Resource 3",
          "identityHash" : "28f0bad7f45b561ea72f51bbef19bcebf8ae5ac",
          "type" : {
            "path" : "/t;hawkular/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "identityHash" : "5316c720e3ab6f14a74c20611d15bf71ecf2bad",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "id" : "<%= uuid_prefix %>-r128"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:54 GMT
- request:
    method: delete
    uri: https://<%= username %>:<%= password %>@127.0.0.1:8443/hawkular/inventory/entity/f;<%= uuid_prefix %>-feed
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 204
      message: No Content
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:54 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:54 GMT
recorded_with: VCR 3.0.3
