---
http_interactions:
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/traversal/type=f
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:46 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '271'
      Link:
      - <https://127.0.0.1:8443/hawkular/inventory/traversal/type=f>; rel="current"
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/f;af0ea377-80f4-4567-af45-105eaa808b92",
          "properties" : {
            "__identityHash" : "6f7052f82072f942f3e402fe127d6133ea5e963"
          },
          "identityHash" : "6f7052f82072f942f3e402fe127d6133ea5e963",
          "id" : "af0ea377-80f4-4567-af45-105eaa808b92"
        } ]
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:46 GMT
recorded_with: VCR 3.0.3
