---
http_interactions:
- request:
    method: get
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/f;feed_may_exist/r;*bla%20does%20not%20exist*
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - localhost:8080
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:40 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '316'
    body:
      encoding: UTF-8
      string: |-
        {
          "errorMsg" : "No Resource found on any of the following paths: [[CanonicalPaths[/t;hawkular/f;feed_may_exist/r;%2Abla%20does%20not%20exist%2A]]]",
          "details" : {
            "entityType" : "Resource",
            "path" : [ [ {
              "paths" : [ "/t;hawkular/f;feed_may_exist/r;%2Abla%20does%20not%20exist%2A" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:40 GMT
recorded_with: VCR 3.0.3
