---
http_interactions:
- request:
    method: get
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/inventory/traversal/f;<%= feed_uuid %>/type=r
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - localhost:8080
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:36 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '1217'
      Link:
      - <http://localhost:8080/hawkular/inventory/traversal/f;<%= feed_uuid %>/type=r>;
        rel="current"
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;platform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem",
          "properties" : {
            "__identityHash" : "b6c67f22d5c2baf8d48d2b85ccd1a93d29bc9a1"
          },
          "name" : "<%= feed_uuid %>_OperatingSystem",
          "identityHash" : "b6c67f22d5c2baf8d48d2b85ccd1a93d29bc9a1",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/rt;Operating%20System",
            "name" : "Operating System",
            "identityHash" : "12ec4befc53b1ed52f39fb292ed1eea8213323",
            "id" : "Operating System"
          },
          "id" : "platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem"
        }, {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;Local~~",
          "properties" : {
            "__identityHash" : "a12d8e9f318357f8aeccd9d955146476325d8b8f"
          },
          "name" : "WildFly Server [Local]",
          "identityHash" : "a12d8e9f318357f8aeccd9d955146476325d8b8f",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/rt;WildFly%20Server",
            "name" : "WildFly Server",
            "identityHash" : "385d354c833f19e97d427c7bfc7c6441b73ef1c",
            "id" : "WildFly Server"
          },
          "id" : "Local~~"
        } ]
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:36 GMT
recorded_with: VCR 3.0.3
