---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/traversal/f;<%= feed_uuid %>/type=r
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 14 Jul 2016 16:23:39 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '1211'
      Link:
      - <http://localhost:8080/hawkular/inventory/traversal/f;<%= feed_uuid %>/type=r>;
        rel="current"
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;platform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem",
          "properties" : {
            "__identityHash" : "dad691902bee0315ce32c6ac94fd49214cf83"
          },
          "name" : "<%= feed_uuid %>_OperatingSystem",
          "identityHash" : "dad691902bee0315ce32c6ac94fd49214cf83",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/rt;Operating%20System",
            "name" : "Operating System",
            "identityHash" : "12ec4befc53b1ed52f39fb292ed1eea8213323",
            "id" : "Operating System"
          },
          "id" : "platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem"
        }, {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;Local~~",
          "properties" : {
            "__identityHash" : "8f7077c6fd492ab39991ce1f7d168a0565fd9e5"
          },
          "name" : "WildFly Server [Local]",
          "identityHash" : "8f7077c6fd492ab39991ce1f7d168a0565fd9e5",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/rt;WildFly%20Server",
            "name" : "WildFly Server",
            "identityHash" : "617542c89b86e3ce52b819c1deae7ca37cf7851",
            "id" : "WildFly Server"
          },
          "id" : "Local~~"
        } ]
    http_version: 
  recorded_at: Thu, 14 Jul 2016 16:23:39 GMT
recorded_with: VCR 3.0.1
