---
http_interactions:
- request:
    method: get
    uri: https://username:password@hawkular.torii.gva.redhat.com/hawkular/inventory/traversal/type=f
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 14 Jul 2016 16:23:36 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '267'
      Link:
      - <http://localhost:8080/hawkular/inventory/traversal/type=f>; rel="current"
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/f;1e8450c5-ef31-4760-ac82-0295dd337ed7",
          "properties" : {
            "__identityHash" : "1529b824c466776d4f26aba71db7cb4788d0d"
          },
          "identityHash" : "1529b824c466776d4f26aba71db7cb4788d0d",
          "id" : "1e8450c5-ef31-4760-ac82-0295dd337ed7"
        } ]
    http_version:
  recorded_at: Thu, 14 Jul 2016 16:23:36 GMT
recorded_with: VCR 3.0.1
