---
http_interactions:
- request:
    method: post
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/feed
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_1123sdncisud6237ui23hjbdscuzsad","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '101'
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/entity/f;feed_1123sdncisud6237ui23hjbdscuzsad
      Date:
      - Thu, 14 Jul 2016 16:23:43 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '178'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;feed_1123sdncisud6237ui23hjbdscuzsad",
          "identityHash" : "c5ef96a36ea11f6a72066f685b5d1d8b9d1daaf",
          "id" : "feed_1123sdncisud6237ui23hjbdscuzsad"
        }
    http_version: 
  recorded_at: Thu, 14 Jul 2016 16:23:43 GMT
recorded_with: VCR 3.0.1
