---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/tenant
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0.rc1 (linux-gnu x86_64) ruby/2.2.4p230
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 18 Feb 2016 22:30:16 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '105'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf",
          "id" : "28026b36-8fe4-4332-84c8-524e173a68bf"
        }
    http_version: 
  recorded_at: Thu, 18 Feb 2016 22:30:16 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/resourceTypes/URL/resources
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0.rc1 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - 28026b36-8fe4-4332-84c8-524e173a68bf
      Tenantid:
      - 28026b36-8fe4-4332-84c8-524e173a68bf
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 18 Feb 2016 22:30:16 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '489'
      Link:
      - <http://localhost:8080/hawkular/inventory/resourceTypes/URL/resources>; rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/e;test/r;536cc3ede5769b60a49774425aedba24",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/rt;URL",
            "id" : "URL"
          },
          "properties" : {
            "trait-collected-on" : 1455834600285,
            "trait-powered-by" : "Apache",
            "created" : 1455833583048,
            "hwk-gui-domainSort" : "bsd.de",
            "trait-remote-address" : "212.86.200.189",
            "url" : "http://bsd.de"
          },
          "id" : "536cc3ede5769b60a49774425aedba24"
        } ]
    http_version: 
  recorded_at: Thu, 18 Feb 2016 22:30:16 GMT
recorded_with: VCR 3.0.1
