---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/tenant
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0.rc1 (linux-gnu x86_64) ruby/2.2.4p230
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 18 Feb 2016 22:30:15 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '105'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf",
          "id" : "28026b36-8fe4-4332-84c8-524e173a68bf"
        }
    http_version: 
  recorded_at: Thu, 18 Feb 2016 22:30:15 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/does%20not%20exist/resourceTypes
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0.rc1 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - 28026b36-8fe4-4332-84c8-524e173a68bf
      Tenantid:
      - 28026b36-8fe4-4332-84c8-524e173a68bf
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 18 Feb 2016 22:30:15 GMT
      X-Total-Count:
      - "-1"
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '3'
      Link:
      - <http://localhost:8080/hawkular/inventory/feeds/does%20not%20exist/resourceTypes>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: "[ ]"
    http_version: 
  recorded_at: Thu, 18 Feb 2016 22:30:15 GMT
recorded_with: VCR 3.0.1
