---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/*bla%20does%20not%20exist*
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Content-Encoding:
      - gzip
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 15 Feb 2016 15:49:14 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '231'
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAALWPwWrDMAyG730KYdilLKRzssw0x503xtgtmOIkcmvwrGK7
        bKHk3We72yMMgyz9v4Q+XTcADL0n/xKODPbAXgneMdDFTwiaLm4GcqDcAqQh
        nrJmLX0Zd4Sziqewh2F4Vo6cmZR9y8pQx56LHe/GpquExrZqm4ZXop1E9chb
        fHhqVCdGXeteI86HT7Uc8NuEWPt+O1p1x3czYUifo5hi8bZSSnafYWeMytiQ
        Wa+pzvgumrh8LGcsB/zRl/ZkZ8xsDOndJn7FcFPZv/AykGXXCrJk62b9ASB2
        xwtsAQAA
    http_version: 
  recorded_at: Mon, 15 Feb 2016 15:49:14 GMT
recorded_with: VCR 3.0.0
