---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/tenant
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/9
      Pragma:
      - no-cache
      Date:
      - Fri, 06 Nov 2015 15:31:36 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '85'
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAKvmUlBQKkgsyVBSsFJQ0i+xNrIwMDJLMjbTtUhLNdE1MTY2
        0rUwSbbQNTUySTU0N040s0hKU9IB6cpMAeshSgNXLQAnmwH5aQAAAA==
    http_version: 
  recorded_at: Fri, 06 Nov 2015 15:31:36 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/resourceTypes
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/9
      Pragma:
      - no-cache
      Date:
      - Fri, 06 Nov 2015 15:31:43 GMT
      X-Total-Count:
      - '17'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '455'
      Link:
      - <http://localhost:8080/hawkular/inventory/resourceTypes>; rel="current"
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAK2UX0/CMBTF3/kUzRLfWMBt4uKenEgMkWhE44PxoYw7XNgf
        0nYaYvjutqMbXTdeTN/gnLPeX87u+oF+BwhZO8y+LHSDrBELHH/sTFbuxPZj
        8GzPdR3b9yLfvnI8uLx28cRfxSPCgreXR2soHk7W1aPi/+Aw/OeBEDCgbBQH
        NAfCxPlPOyCYJfnmwhkv95RBdhyX4wyqo5sAUm1J0zFNos2SFAQVKwhoUMJC
        iiFxFNkkyDMpIqC0IBqFpkuIk2qSYQFZQfYagCrK6VIyOfo9SdezdC9eBZBv
        0FuQNlJNCaNZJqGmmGFalCTSV0M3JIoim8SYT8M7XsyUJN1ihIdUR6KoutFK
        YJcW+wxypleiGXUlJ9nsplKKN1C3kvMf9/Ows7lV6FhDjppAs8Ud2yTikmEG
        KZ9R7TSlSdFP2eSQTHVA+xNGWfm3k4L+SltqzSI1o9P53c7PPNdP7XZ7aTlG
        icrV2UXv8WqelmOS55XgnOKIHXdogXO+t/pNoGRQKyHp+nyTjA/4Z1ummHBA
        cSXH1WV+u+kWWAeRjCElJFnPREzihqX4MENSbDtNcguphoRS5MEBff4BYg+j
        FXAJAAA=
    http_version: 
  recorded_at: Fri, 06 Nov 2015 15:31:43 GMT
recorded_with: VCR 3.0.0
