---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/tenant
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/9
      Pragma:
      - no-cache
      Date:
      - Fri, 06 Nov 2015 19:28:58 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '85'
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAKvmUlBQKkgsyVBSsFJQ0i+xNrIwMDJLMjbTtUhLNdE1MTY2
        0rUwSbbQNTUySTU0N040s0hKU9IB6cpMAeshSgNXLQAnmwH5aQAAAA==
    http_version:
  recorded_at: Fri, 06 Nov 2015 19:28:58 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/snert/resourceTypes/WildFly%20Server/resources
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/9
      Pragma:
      - no-cache
      Date:
      - Fri, 06 Nov 2015 19:28:58 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '177'
      Link:
      - <http://localhost:8080/hawkular/inventory/feeds/snert/resourceTypes/WildFly%20Server/resources>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAItWqOZSUFAqSCzJUFKwUlDSL7E2sjAwMksyNtO1SEs10TUx
        NjbStTBJttA1NTJJNTQ3TjSzSErTT7UuSS0u0U+zLs5LLSrRL4LQdT75yYk5
        dXVKOiBDSyoLUkGGgmyghh0l1uGZOSluOZWqRgbBqUVlqUVge4BG5yXmgm1S
        gipQQJXOTMEmCZSrBbsTh26FaLC9sRDPQM1A9SZXrUIsAH0JV21CAQAA
    http_version:
  recorded_at: Fri, 06 Nov 2015 19:28:58 GMT
recorded_with: VCR 3.0.0
