---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/tenant
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0.rc1 (linux-gnu x86_64) ruby/2.2.4p230
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 18 Feb 2016 22:30:15 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '105'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf",
          "id" : "28026b36-8fe4-4332-84c8-524e173a68bf"
        }
    http_version: 
  recorded_at: Thu, 18 Feb 2016 22:30:15 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/resourceTypes/Datasource/resources
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0.rc1 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - 28026b36-8fe4-4332-84c8-524e173a68bf
      Tenantid:
      - 28026b36-8fe4-4332-84c8-524e173a68bf
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 18 Feb 2016 22:30:16 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '863'
      Link:
      - <http://localhost:8080/hawkular/inventory/feeds/f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/resourceTypes/Datasource/resources>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/r;Local~~/r;Local~%2Fsubsystem=datasources%2Fdata-source=ExampleDS",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/rt;Datasource",
            "name" : "Datasource",
            "id" : "Datasource"
          },
          "name" : "ExampleDS",
          "id" : "Local~/subsystem=datasources/data-source=ExampleDS"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/r;Local~~/r;Local~%2Fsubsystem=datasources%2Fdata-source=KeycloakDS",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/rt;Datasource",
            "name" : "Datasource",
            "id" : "Datasource"
          },
          "name" : "KeycloakDS",
          "id" : "Local~/subsystem=datasources/data-source=KeycloakDS"
        } ]
    http_version: 
  recorded_at: Thu, 18 Feb 2016 22:30:16 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/resources/Local~%2Fsubsystem=datasources%2Fdata-source=ExampleDS/data?dataType=configuration
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0.rc1 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - 28026b36-8fe4-4332-84c8-524e173a68bf
      Tenantid:
      - 28026b36-8fe4-4332-84c8-524e173a68bf
      Content-Type:
      - application/json
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 18 Feb 2016 22:30:16 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '500'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "No DataEntity found on any of the following paths: [[CanonicalPaths[/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/r;Local~%2Fsubsystem=datasources%2Fdata-source=ExampleDS/d;configuration]]]",
          "details" : {
            "entityType" : "DataEntity",
            "path" : [ [ {
              "paths" : [ "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/r;Local~%2Fsubsystem=datasources%2Fdata-source=ExampleDS/d;configuration" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Thu, 18 Feb 2016 22:30:16 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/resources/Local~%2Fsubsystem=datasources%2Fdata-source=KeycloakDS/data?dataType=configuration
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0.rc1 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - 28026b36-8fe4-4332-84c8-524e173a68bf
      Tenantid:
      - 28026b36-8fe4-4332-84c8-524e173a68bf
      Content-Type:
      - application/json
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 18 Feb 2016 22:30:16 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '502'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "No DataEntity found on any of the following paths: [[CanonicalPaths[/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/r;Local~%2Fsubsystem=datasources%2Fdata-source=KeycloakDS/d;configuration]]]",
          "details" : {
            "entityType" : "DataEntity",
            "path" : [ [ {
              "paths" : [ "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;f1cb161f-4de3-44b9-a2a4-bdc5a2064f88/r;Local~%2Fsubsystem=datasources%2Fdata-source=KeycloakDS/d;configuration" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Thu, 18 Feb 2016 22:30:16 GMT
recorded_with: VCR 3.0.1
